/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.webshop;

/**
 * Local interface for WebShop.
 * @build-nightlabs.xml generated
 */
public interface WebShopLocal
   extends javax.ejb.EJBLocalObject
{

   public java.util.Collection getWebCustomers( java.util.Set webCustomerIDs,java.lang.String[] fetchGroups,int maxFetchDepth ) ;

   public void createWebCustomer( java.lang.String webCustomerID,java.lang.String password,org.nightlabs.jfire.person.Person person ) throws org.nightlabs.jfire.webshop.DoublicateIDException;

   public boolean isWebCustomerIDExisting( java.lang.String webCustomerID ) ;

   public org.nightlabs.jfire.webshop.WebCustomer storeWebCustomer( org.nightlabs.jfire.webshop.WebCustomer webCustomer,boolean get,java.lang.String[] fetchGroups,int maxFetchDepth ) ;

   public java.lang.String getNewPassword( org.nightlabs.jfire.webshop.id.WebCustomerID webCustomerID ) ;

}
