/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.webshop;

/**
 * Remote interface for WebShop.
 * @build-nightlabs.xml generated
 */
public interface WebShop
   extends javax.ejb.EJBObject
{

   public java.util.Collection getWebCustomers( java.util.Set webCustomerIDs,java.lang.String[] fetchGroups,int maxFetchDepth )
      throws java.rmi.RemoteException;

   public void createWebCustomer( java.lang.String webCustomerID,java.lang.String password,org.nightlabs.jfire.person.Person person )
      throws org.nightlabs.jfire.webshop.DoublicateIDException, java.rmi.RemoteException;

   public boolean isWebCustomerIDExisting( java.lang.String webCustomerID )
      throws java.rmi.RemoteException;

   public org.nightlabs.jfire.webshop.WebCustomer storeWebCustomer( org.nightlabs.jfire.webshop.WebCustomer webCustomer,boolean get,java.lang.String[] fetchGroups,int maxFetchDepth )
      throws java.rmi.RemoteException;

   public java.lang.String getNewPassword( org.nightlabs.jfire.webshop.id.WebCustomerID webCustomerID )
      throws java.rmi.RemoteException;

}
