/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.webshop;

/**
 * Home interface for WebShop.
 * @build-nightlabs.xml generated
 */
public interface WebShopHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/WebShop";
   public static final String JNDI_NAME="WebShop";

   public org.nightlabs.jfire.webshop.WebShop create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
