/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.webshop;

/**
 * Local home interface for WebShop.
 * @build-nightlabs.xml generated
 */
public interface WebShopLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/WebShopLocal";
   public static final String JNDI_NAME="WebShopLocal";

   public org.nightlabs.jfire.webshop.WebShopLocal create()
      throws javax.ejb.CreateException;

}
