/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.webshop;

/**
 * Session layer for WebShop.
 * @build-nightlabs.xml generated
 */
public class WebShopSession
   extends org.nightlabs.jfire.webshop.WebShopBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {

      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext() 
   {
      super.unsetSessionContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbRemove();
   }

}
