/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.reporting.trade;

/**
 * Home interface for jfire/ejb/JFireReportingTrade/ReportManagerTrade.
 * @build-nightlabs.xml generated
 */
public interface ReportManagerTradeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/jfire/ejb/JFireReportingTrade/ReportManagerTrade";
   public static final String JNDI_NAME="jfire/ejb/JFireReportingTrade/ReportManagerTrade";

   public org.nightlabs.jfire.reporting.trade.ReportManagerTrade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
