/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.reporting.trade;

/**
 * Session layer for jfire/ejb/JFireReportingTrade/ReportManagerTrade.
 * @build-nightlabs.xml generated
 */
public class ReportManagerTradeSession
   extends org.nightlabs.jfire.reporting.trade.ReportManagerTradeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext() 
   {
      super.unsetSessionContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbRemove();
   }

}
