/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.reporting.trade;

/**
 * Local home interface for jfire/ejb/JFireReportingTrade/ReportManagerTrade.
 * @build-nightlabs.xml generated
 */
public interface ReportManagerTradeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/jfire/ejb/JFireReportingTrade/ReportManagerTradeLocal";
   public static final String JNDI_NAME="jfire/ejb/JFireReportingTrade/ReportManagerTradeLocal";

   public org.nightlabs.jfire.reporting.trade.ReportManagerTradeLocal create()
      throws javax.ejb.CreateException;

}
