/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.reporting.trade;

/**
 * Local interface for jfire/ejb/JFireReportingTrade/ReportManagerTrade.
 * @build-nightlabs.xml generated
 */
public interface ReportManagerTradeLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * This method is called by the datastore initialization mechanism.
    * @throws ModuleException
    */
   public void initializeScripting(  ) throws org.nightlabs.ModuleException;

   /**
    * This method is called by the datastore initialization mechanism.
    * @throws ModuleException
    */
   public void initializeReporting(  ) throws org.nightlabs.ModuleException;

}
