/* *****************************************************************************
 * JFire - it's hot - Free ERP System - http://jfire.org                       *
 * Copyright (C) 2004-2005 NightLabs - http://NightLabs.org                    *
 *                                                                             *
 * This library is free software; you can redistribute it and/or               *
 * modify it under the terms of the GNU Lesser General Public                  *
 * License as published by the Free Software Foundation; either                *
 * version 2.1 of the License, or (at your option) any later version.          *
 *                                                                             *
 * This library is distributed in the hope that it will be useful,             *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of              *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU           *
 * Lesser General Public License for more details.                             *
 *                                                                             *
 * You should have received a copy of the GNU Lesser General Public            *
 * License along with this library; if not, write to the                       *
 *     Free Software Foundation, Inc.,                                         *
 *     51 Franklin St, Fifth Floor,                                            *
 *     Boston, MA  02110-1301  USA                                             *
 *                                                                             *
 * Or get it online :                                                          *
 *     http://www.gnu.org/copyleft/lesser.html                                 *
 *                                                                             *
 *                                                                             *
 ******************************************************************************/

package org.nightlabs.jfire.reporting.oda.client.jdojs;

import java.util.Map;

import org.eclipse.datatools.connectivity.oda.IResultSet;
import org.eclipse.datatools.connectivity.oda.IResultSetMetaData;
import org.eclipse.datatools.connectivity.oda.OdaException;
import org.nightlabs.jfire.base.ui.login.Login;
import org.nightlabs.jfire.reporting.ReportManager;
import org.nightlabs.jfire.reporting.ReportManagerUtil;
import org.nightlabs.jfire.reporting.oda.jdojs.AbstractJDOJSProxy;
import org.nightlabs.jfire.reporting.oda.jdojs.JDOJSResultSet;
import org.nightlabs.jfire.reporting.oda.jdojs.JDOJSResultSetMetaData;

/**
 * @author Alexander Bieber <alex[AT]nightlabs[DOT]de>
 *
 */
public class ClientJDOJSProxy extends AbstractJDOJSProxy {

	/* (non-Javadoc)
	 * @see org.eclipse.datatools.connectivity.oda.IQuery#prepare(java.lang.String)
	 */
	public void prepare(String prepareScript) throws OdaException {
		setPrepareScript(prepareScript);
		getMetaData();
	}

	private JDOJSResultSetMetaData metaData;
	
	/* (non-Javadoc)
	 * @see org.eclipse.datatools.connectivity.oda.IQuery#getMetaData()
	 */
	public IResultSetMetaData getMetaData() throws OdaException {
		if (metaData == null)
			metaData = fetchMetaData(getPrepareScript());
		return metaData;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.datatools.connectivity.oda.IQuery#executeQuery()
	 */
	public IResultSet executeQuery() throws OdaException {
		JDOJSResultSet resultSet = fetchResultSet(
				(JDOJSResultSetMetaData)getMetaData(),
				getFetchScript(),
//				getParameterMetaData(),
				getNamedParameters()
			);
//		resultSet.setMetaDataAndValidate((ResultSetMetaData)getMetaData());
		return resultSet;
	}
	
	/**
	 * Fetches the ResultSetMetaData generated by the prepareScript
	 * of this Query.
	 */
	public static JDOJSResultSetMetaData fetchMetaData(String prepareScript)
	throws OdaException
	{
		try {
			ReportManager reportManager = ReportManagerUtil.getHome(Login.getLogin().getInitialContextProperties()).create();
			return reportManager.prepareJDOJSQuery(prepareScript);
		} catch (Throwable t) {
			throw new OdaException("Error fetching JDOJS DataSet metaData: "+t.getClass().getName()+", messge"+t.getMessage()); //$NON-NLS-1$ //$NON-NLS-2$
		}
	}
	
	/**
	 * Fetches the ResultSet generated by the prepareScript
	 * of this Query.
	 */
	public static JDOJSResultSet fetchResultSet(
			JDOJSResultSetMetaData metaData,
			String fetchScript,
//			IParameterMetaData parameterMetaData,
			Map<String, Object> parameters
		)
	throws OdaException
	{
		try {
			ReportManager reportManager = ReportManagerUtil.getHome(Login.getLogin().getInitialContextProperties()).create();
			return reportManager.fetchJDOJSResultSet(
					metaData, fetchScript,
					parameters
				);
		} catch (Throwable t) {
			throw new OdaException("Error fetching JDOJS ResultSet: "+t.getClass().getName()+", message "+t.getMessage()); //$NON-NLS-1$ //$NON-NLS-2$
		}
	}
}
